# Generated by Django 5.2.1 on 2025-05-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reminder_reminder_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='name',
        ),
    ]
